# fly.toml app configuration file generated for late-dew-7758 on 2023-11-06T14:00:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "late-dew-7758"
primary_region = "arn"

[build]

[env]
  PORT = "3000" # add this
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
